---
title: "short_demo"
output: html_document
---

```{r setup, include=FALSE}
library(gofigR)
library(ggplot2)
library(cowplot)
library(ComplexHeatmap)
library(patchwork)
library(ggplotify)
library(tidyverse)
library(RColorBrewer)

knitr::opts_chunk$set(echo = TRUE)
gofigR::enable()
```

This markdown illustrates GoFigr integration with Rmarkdown. Notice how every figure gets a unique QR code which links to the specific revision on GoFigr. You can navigate to that revision and view the source code, environment details, and figure data.

## Manual figure capture

```{r manual_capture, fig.width=8, fig.height=8}
publish({
  base::plot(pressure, main="Pressure vs temperature")
  text(200, 50, "Note the non-linear relationship")
}, data=pressure, figure_name="Pressure vs temperature")

publish({
  # The mtcars dataset:
  data <- as.matrix(mtcars)

  coul <- colorRampPalette(brewer.pal(8, "PiYG"))(25)
  heatmap(data, scale="column", col = coul, main="Visualizing mtcars")
}, data=mtcars, figure_name="Cars")
```

## Automatic figure capture for ggplot2

```{r correlations, fig.width=7, fig.height=7}
scatter <- ggplot(mtcars, aes(x=wt, y=mpg, color=cyl, size=cyl)) +
      geom_point() +
      theme(legend.position="none") + ggtitle("Correlations")

print(scatter)
```
